# Generated by Django 5.0.2 on 2024-02-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_matchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='username_1',
            new_name='usermove_1',
        ),
        migrations.RenameField(
            model_name='matchhistory',
            old_name='username_2',
            new_name='usermove_2',
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_matches', to='main_app.bumpevent'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two_matches', to='main_app.bumpevent'),
        ),
    ]
