# Generated by Django 5.0.2 on 2024-02-12 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_username_1_matchhistory_usermove_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='usermove_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermove_1_matches', to='main_app.bumpevent'),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='usermove_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermove_2_matches', to='main_app.bumpevent'),
        ),
    ]
