# Generated by Django 5.0.2 on 2024-02-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_matchhistory_player_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='usermove_1',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='usermove_2',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='userchoice_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='userchoice_2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
