# Generated by Django 5.0.2 on 2024-02-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_matchhistory_usermove_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumpevent',
            name='choice',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Paper', 'Paper'), ('Scissors', 'Scissors')], max_length=100),
        ),
    ]
