# Generated by Django 5.0.2 on 2024-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_bumpevent_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bumpevent',
            name='server_time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
